### ISSUE TITLE
Not Self-hostable?

### ISSUE THREAD

**Issue by mzch** [kee-org/keevault#9]
There are hard coded domains and it seems to be no effective configurations to them. I'd like to host keevault on my VPS. Any ideas?

**Comment by rentasad** [comment]
I tried also to install it self-hosted aind failed also.
For your test my Dockerfile:

```
FROM ubuntu:latest
VOLUME app /app

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Minsk
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV NODE_PATH /install/node_modules/
ENV PATH /install/node_modules/.bin:$PATH
RUN apt update && apt install -y locales software-properties-common git npm && rm -rf /var/lib/apt/lists/* \
    && localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8
ENV LANG de_DE.utf8


WORKDIR /app
EXPOSE 8080
COPY app/package*.json ./
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
EXPOSE 8080
```

My Run Command is
`sudo docker run -it --rm  --name keevault -v /home/gustini/dockerFiles/keevault/app:/app gustini/keevault2`

But I don't know which ports I have to bind. Netstat dont give me a listen port.
Is there a web frontend? 
Is there only a Backend for requests and I need a separate client?
Please help!

**Comment by luckyrat** [comment]
Kee Vault is not designed to be run with a custom or self-hosted backend for orchestrating access to kdbx files. If you're developing enhancements to the PWA it should be pretty easy to see where you can make changes to back-end communication and in 99% of cases you won't need to talk to the backend at all because you can just use the demo kdbx file, potentially modifying it using KeePass or another kdbx editor if there is some feature that it does not adequately demonstrate.

If you want to discuss such development, please consider using the community forum for a faster response: https://forum.kee.pm
